sudo: required

language: go

go:
- 1.9

branches:
  only:
  - master

services:
- docker

install:
- go get -u github.com/golang/dep/cmd/dep

script:
- make deps
- make
- make push

notifications:
  email: false