apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-demo
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubecon-demo
  template:
    metadata:
      labels:
        app: kubecon-demo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kubecon-demo
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kubecon-demo
        image: hweicdl/kubecon-demo:v0.0.3
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
