apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-demo
  template:
    metadata:
      labels:
        app: kubecon-demo
    spec:
      containers:
      - name: kubecon-demo
        image: hweicdl/kubecon-demo:v0.0.1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
